import 'models/pagination.dart';
import 'models/send_result.dart';
import 'models/session.dart';
import 'events/provider_event.dart';

/// Interface for a chat provider.
///
/// A chat provider handles authentication, fetching conversations and messages,
/// and sending messages for a specific chat service (e.g., Telegram, WhatsApp, Mock).
abstract interface class IChatProvider {
  /// Attempts to restore an existing session from persistent storage.
  ///
  /// Returns the restored [ProviderSession] if successful, or `null` if no session
  /// was found or it has expired.
  Future<ProviderSession?> restoreSession();

  /// Logs in to the chat service using the provided [params].
  ///
  /// Throws a [ProviderException] if login fails.
  Future<ProviderSession> login(LoginParams params);

  /// Logs out of the current session and clears any stored credentials.
  Future<void> logout();

  /// Fetches a paginated list of conversations.
  ///
  /// [cursor] can be used to fetch the next page.
  /// [limit] specifies the maximum number of conversations to return.
  /// [query] can be used to filter conversations by name or content.
  Future<ConversationPage> listConversations({String? cursor, int limit = 50, String? query});

  /// Fetches a paginated list of messages for a specific conversation.
  ///
  /// [beforeMessageId] is used for "load earlier" pagination.
  /// [limit] specifies the maximum number of messages to return.
  Future<MessagePage> listMessages({required String conversationId, String? beforeMessageId, int limit = 50});

  /// Sends a message to the specified conversation.
  ///
  /// [clientMessageId] is a unique ID generated by the client to track this
  /// message before it is assigned a server-side ID.
  ///
  /// Returns a [SendResult] indicating the outcome of the send operation.
  Future<SendResult> sendMessage({required String conversationId, required String clientMessageId, required String text});

  /// Marks all messages in the specified conversation as read.
  Future<void> markAsRead(String conversationId);

  /// A stream of events from the chat service (e.g., new messages, status updates).
  Stream<ProviderEvent> get events;

  /// The currently active session, or `null` if the user is not authenticated.
  ProviderSession? get currentSession;
}
